### ISSUE TITLE
Assembly instruction suffix 's' in thumb functions

### ISSUE THREAD

**Issue by laqieer** [camthesaxman/gbadisasm#4]
# Problem

The disassembly result includes instruction suffix 's' in thumb functions, which causes following errors:
 
Error: instruction not supported in Thumb16 mode -- `subs r0,r0,#4'

Error: instruction not supported in Thumb16 mode -- `subs r1,r1,#4'

Error: instruction not supported in Thumb16 mode -- `adds r0,r0,#1'

Cross toolchain version: arm-none-eabi-gcc (devkitARM release 53) 9.1.0

# Request

Remove instruction suffix 's' in thumb functions.

**Comment by jiangzhengwenjz** [comment]
You need `.syntax unified`. 
Those instructions actually always update CPSR flags in thumb mode so syntax won't make a difference to the output. 

And check this branch for latest update https://github.com/PikalaxALT/gbadisasm/tree/new_features

**Comment by atasro2** [comment]
this issue is irrelevant and should be closed but it will never be because camthesaxman:tm:
