### ISSUE TITLE
double free crash

### ISSUE THREAD

**Issue by Strugglemeat** [camthesaxman/gbadisasm#6]
> ./gbadisasm FlappyBird.gba

double free or corruption (out)
zsh: IOT instruction (core dumped)

**Comment by jiangzhengwenjz** [comment]
Hello, you can try with [my fork](https://github.com/jiangzhengwenjz/gbadisasm)
I got the ROM from [here](http://www.jayvanhutten.com/flappy/) and there was no issue reported w/o a config file.

**Comment by Strugglemeat** [comment]
it worked with your fork - thanks
